# Site settings
baseurl: ""
url: "https://www.bersteinwithlove.com"
api: "https://api.bersteinwithlove.com"
contact: "hello@bersteinwithlove.com"
keys:
    google-maps: AIzaSyDrD_iLTZozQ0COxNAWTCsSV7MloGaLDD8
collections:
    people:
        output: false
    our-story:
        output: false
    registries:
        output: false
    wedding:
        output: false

# Build settings
permalink: pretty
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, README.md, Vagrantfile]
include: [_redirects]
gems:
    - jekyll-sitemap

# Frontmatter defaults
defaults:
    -
        scope:
            path: ""
        values:
            lang: "en"
