# Site settings
baseurl: ""
url: "https://www.bersteinwithlove.com"

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, README.md, Vagrantfile]
gems:
    - jekyll-sitemap

# Frontmatter defaults
defaults:
    -
        scope:
            path: ""
        values:
            lang: "en"
